[project]
name = "chat_node"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = ["fastapi", "httpx", "uvicorn"]

[project.optional-dependencies]
dev = ["black", "isort", "pylint[spelling]", "mypy"]
