services:
  chat-node:
    build:
      context: ./chat_node
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8001:8001"
    networks:
      - chat
  main-node:
    build:
      context: ./main_node
      dockerfile: Dockerfile
    ports:
    - "127.0.0.1:8000:8000"
    networks:
      - chat

networks:
  chat:
    external: true