name: Check code

on: [push]

jobs:
  check-python-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install applications and modules
        run: |
          pip install ./main_node[dev] ./client[dev] ./chat_node[dev]
      - name: Format Check
        if: always()
        run: make format
      - name: Lint Check
        if: always()
        run: make lint
      - name: Imports check
        if: always()
        run: make imports
      - name: Typing check
        if: always()
        run: make types
